name: reviewdog
on: [pull_request]
jobs:
  golangci-lint:
    name: runner/golangci-lint
    runs-on: ubuntu-16.04
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          golangci_lint_flags: "--enable-all --timeout=10m --exclude-use-default=false"
